//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_First
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tire()
        {
            this.OrdersDetails = new HashSet<OrdersDetail>();
            this.TireAndRimSuppliers = new HashSet<TireAndRimSupplier>();
        }
    
        public int TiresId { get; set; }
        public int Diameter { get; set; }
        public int Thickness { get; set; }
        public int Width { get; set; }
        public string Brand { get; set; }
        public string Season { get; set; }
        public System.DateTime YearOfProduction { get; set; }
        public string Type { get; set; }
        public System.DateTime DateOfReceipt { get; set; }
        public Nullable<short> UnıtsInStock { get; set; }
        public Nullable<decimal> ArrivalPrice { get; set; }
        public Nullable<decimal> SalePrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersDetail> OrdersDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TireAndRimSupplier> TireAndRimSuppliers { get; set; }
    }
}
